name: Node.js CI

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint:ci

  test:

    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      os-swift:
        env:
          SWIFT_STORAGE_USERNAME: tester12345679
        # Docker Hub image
        # image: mdouchement/openstackswift
        image: trollkarlen/openstackswift
        #
        ports:
          # Opens tcp port 5000 on the host and service container
          - 5000:5000

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo '{"endpointUrl":"http://127.0.0.1:5000/v3","username":"tester12345679","password":"testing","projectName":"test","domainName":"Default","endpointUrlInterface":"public","regionId":"RegionOne"}' > test/credentials.ksv3.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test
